from __future__ import annotations

from typing import Final, Literal

# Errori "strutturali" del dominio/esito
SISTEMA_ERRORE_CODICE_MANCANTE: Final = "SISTEMA_ERRORE_CODICE_MANCANTE"
SISTEMA_ERRORE_MESSAGGIO_NON_DISPONIBILE: Final = "SISTEMA_ERRORE_MESSAGGIO_NON_DISPONIBILE"
SISTEMA_ERRORE_CODICE_NON_MAPPATO_DEBUG: Final = "SISTEMA_ERRORE_CODICE_NON_MAPPATO_DEBUG"

# Fallback focus auto-impostato
SISTEMA_SELEZIONE_AUTOMATICA_EFFETTUATA: Final = "SISTEMA_SELEZIONE_AUTOMATICA_EFFETTUATA"
SISTEMA_TIPO_FOCUS_NON_PREVISTO_DEBUG: Final = "SISTEMA_TIPO_FOCUS_NON_PREVISTO_DEBUG"
SISTEMA_TEMPLATE_EVENTO_MANCANTE_DEBUG: Final = "SISTEMA_TEMPLATE_EVENTO_MANCANTE_DEBUG"
SISTEMA_PLACEHOLDER_TEMPLATE_MANCANTE_DEBUG: Final = "SISTEMA_PLACEHOLDER_TEMPLATE_MANCANTE_DEBUG"

# Focus cartella impostato (testo standard)
SISTEMA_FOCUS_CARTELLA_IMPOSTATO: Final = "SISTEMA_FOCUS_CARTELLA_IMPOSTATO"
SISTEMA_FOCUS_RESET_RIGA_COLONNA: Final = "SISTEMA_FOCUS_RESET_RIGA_COLONNA"

# Fine turno
SISTEMA_TURNO_PASSATO: Final = "SISTEMA_TURNO_PASSATO"
SISTEMA_RECLAMO_ASSOCIATO_TOMBOLA: Final = "SISTEMA_RECLAMO_ASSOCIATO_TOMBOLA"
SISTEMA_RECLAMO_ASSOCIATO_RIGA: Final = "SISTEMA_RECLAMO_ASSOCIATO_RIGA"
SISTEMA_RECLAMO_ASSOCIATO_RIGA_NON_DISPONIBILE: Final = "SISTEMA_RECLAMO_ASSOCIATO_RIGA_NON_DISPONIBILE"

# Reclamo inviato / riferimento
SISTEMA_RECLAMO_INVIATO: Final = "SISTEMA_RECLAMO_INVIATO"
SISTEMA_RIFERIMENTO_TOMBOLA: Final = "SISTEMA_RIFERIMENTO_TOMBOLA"
SISTEMA_RIFERIMENTO_RIGA: Final = "SISTEMA_RIFERIMENTO_RIGA"
SISTEMA_RIFERIMENTO_RIGA_NON_DISPONIBILE: Final = "SISTEMA_RIFERIMENTO_RIGA_NON_DISPONIBILE"

# Esito reclamo
SISTEMA_ESITO_RECLAMO: Final = "SISTEMA_ESITO_RECLAMO"
SISTEMA_ESITO_RECLAMO_MOTIVO: Final = "SISTEMA_ESITO_RECLAMO_MOTIVO"
SISTEMA_ESITO_RECLAMO_TURNO: Final = "SISTEMA_ESITO_RECLAMO_TURNO"
SISTEMA_ESITO_RECLAMO_NUMERO_ESTRATTO: Final = "SISTEMA_ESITO_RECLAMO_NUMERO_ESTRATTO"

# Evento sconosciuto
SISTEMA_EVENTO_NON_SUPPORTATO: Final = "SISTEMA_EVENTO_NON_SUPPORTATO"
SISTEMA_EVENTO_NON_SUPPORTATO_DEBUG: Final = "SISTEMA_EVENTO_NON_SUPPORTATO_DEBUG"


Codici_Messaggi_Sistema = Literal[
    "SISTEMA_ERRORE_CODICE_MANCANTE",
    "SISTEMA_ERRORE_MESSAGGIO_NON_DISPONIBILE",
    "SISTEMA_ERRORE_CODICE_NON_MAPPATO_DEBUG",

    "SISTEMA_SELEZIONE_AUTOMATICA_EFFETTUATA",
    "SISTEMA_TIPO_FOCUS_NON_PREVISTO_DEBUG",
    "SISTEMA_TEMPLATE_EVENTO_MANCANTE_DEBUG",
    "SISTEMA_PLACEHOLDER_TEMPLATE_MANCANTE_DEBUG",

    "SISTEMA_FOCUS_CARTELLA_IMPOSTATO",
    "SISTEMA_FOCUS_RESET_RIGA_COLONNA",

    "SISTEMA_TURNO_PASSATO",
    "SISTEMA_RECLAMO_ASSOCIATO_TOMBOLA",
    "SISTEMA_RECLAMO_ASSOCIATO_RIGA",
    "SISTEMA_RECLAMO_ASSOCIATO_RIGA_NON_DISPONIBILE",

    "SISTEMA_RECLAMO_INVIATO",
    "SISTEMA_RIFERIMENTO_TOMBOLA",
    "SISTEMA_RIFERIMENTO_RIGA",
    "SISTEMA_RIFERIMENTO_RIGA_NON_DISPONIBILE",

    "SISTEMA_ESITO_RECLAMO",
    "SISTEMA_ESITO_RECLAMO_MOTIVO",
    "SISTEMA_ESITO_RECLAMO_TURNO",
    "SISTEMA_ESITO_RECLAMO_NUMERO_ESTRATTO",

    "SISTEMA_EVENTO_NON_SUPPORTATO",
    "SISTEMA_EVENTO_NON_SUPPORTATO_DEBUG",
]
